project:
  type: default
  output-dir: _output

title: "From search step to output mask in a guitar tablature neural network"

format:
  html:
    embed-resources: true
    page-layout: full
    link-external-icon: true
    link-external-newwindow: true
    code-copy: true
    smooth-scroll: true
    theme:
      - assets/theme/theme.scss
    highlight-style: github-dark
    mainfont: "Space Grotesk"
    fontsize: 16px
    fig-align: center
    toc: true
    grid:
      sidebar-width: 250px
      body-width: 720px
      margin-width: 250px
      gutter-width: 1.5em

execute:
  freeze: true
